services:
  app:
    build:
      context: .
      target: development
    working_dir: /build
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: postgres
    restart: always
    volumes:
      - javashop-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}

volumes:
  javashop-data:

