services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: postgres
    volumes:
      - javashop-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}

volumes:
  javashop-data:

